doctrine:
    dbal:
        driver: 'pdo_mysql'
        charset: utf8mb4

        host: '%env(DATABASE_HOST)%'
        dbname: '%env(MYSQL_DATABASE)%'
        user: '%env(MYSQL_USER)%'
        password: '%env(MYSQL_PASSWORD)%'
        types:
            userUuid:        BelkinDom\Adapters\Database\Doctrine\Type\UserUuidType
            fileUuid:        BelkinDom\Adapters\Database\Doctrine\Type\FileUuidType
            productUuid:     BelkinDom\Adapters\Database\Doctrine\Type\ProductUuidType
            partnerUuid:     BelkinDom\Adapters\Database\Doctrine\Type\PartnerUuidType
            categoryUuid:    BelkinDom\Adapters\Database\Doctrine\Type\CategoryUuidType
            galleryUuid:     BelkinDom\Adapters\Database\Doctrine\Type\GalleryUuidType
            galleryItemUuid: BelkinDom\Adapters\Database\Doctrine\Type\GalleryItemUuidType
            rugStencilUuid:  BelkinDom\Adapters\Database\Doctrine\Type\RugStencilUuidType
            postUuid:        BelkinDom\Adapters\Database\Doctrine\Type\PostUuidType
            reviewUuid:      BelkinDom\Adapters\Database\Doctrine\Type\ReviewUuidType
            faqUuid:         BelkinDom\Adapters\Database\Doctrine\Type\FaqUuidType
            orderUuid:       BelkinDom\Adapters\Database\Doctrine\Type\OrderUuidType
            orderItemUuid:   BelkinDom\Adapters\Database\Doctrine\Type\OrderItemUuidType
            contactUuid:     BelkinDom\Adapters\Database\Doctrine\Type\ContactUuidType
            configUuid:      BelkinDom\Adapters\Database\Doctrine\Type\ConfigUuidType
            translatable:    BelkinDom\Adapters\Database\Doctrine\Type\TranslatableType
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: false
        mappings:
            Store:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Adapters/Database/Doctrine/Resources/config'
                prefix: 'BelkinDom\Store'
                alias: Store
